[project]
name = "attempt2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "brainflow>=5.16.0",
    "matplotlib>=3.10.0",
]
